platform: linux

image_resource:
  type: docker-image
  source:
    repository: engineerbetter/hugo
    tag: 30.2

inputs:
- name: eb-hugo
outputs:
- name: generated-site
- name: tarball

run:
  path: ci/tasks/hugo-build.sh
  dir: eb-hugo
