platform: linux

image_resource:
  type: docker-image
  source:
    repository: engineerbetter/hugo
    tag: latest

inputs:
- name: eb-hugo

run:
  path: ci/tasks/smoke-tests.sh
  dir: eb-hugo

params:
  HOST:
