platform: linux

image_resource:
  type: docker-image
  source:
    repository: engineerbetter/pcf-ops
    tag: latest

inputs:
- name: eb-hugo
- name: input

outputs:
- name: output

run:
  path: eb-hugo/ci/tasks/untar.sh
