---
resources:
- name: eb-hugo
  type: git
  source:
    uri: https://github.com/engineerbetter/engineerbetter-hugo.git

- name: site-tarball
  type: s3
  source:
    bucket: eb-hugo-builds
    region_name: eu-west-2
    versioned_file: eb-hugo-built.tar.gz
    access_key_id: {{concourse_ci_s3_access_key}}
    secret_access_key: {{concourse_ci_s3_secret_key}}

- name: cf-dev
  type: cf
  source:
    <<: &cf-params
      api: https://api.run.pivotal.io
      username: systems@engineerbetter.com
      password: {{systems_cf_password}}
      organization: engineerbetter
      skip_cert_check: false
    space: development

- name: cf-staging
  type: cf
  source:
    <<: *cf-params
    space: staging

- name: cf-prod
  type: cf
  source:
    <<: *cf-params
    space: production

jobs:
- name: build-site
  serial: true
  plan:
  - get: eb-hugo
    trigger: true
  - task: hugo
    file: eb-hugo/ci/tasks/hugo-build.yml
  - aggregate:
    - put: site-tarball
      params:
        file: tarball/eb-hugo-built.tar.gz
    - put: cf-dev
      params:
        manifest: eb-hugo/ci/assets/hugo-manifest-dev.yml

- name: test-dev
  public: false
  serial: true
  plan:
  - get: eb-hugo
  - get: site-tarball
    passed: [build-site]
    trigger: true
  - task: smoke-tests
    file: eb-hugo/ci/tasks/smoke-tests.yml
    params:
      HOST: http://eb-hugo-dev.engineerbetter.com

- name: deploy-site-staging
  public: false
  serial: true
  plan:
  - get: eb-hugo
  - get: site-tarball
    passed: [test-dev]
    trigger: true
  - task: untar
    file: eb-hugo/ci/tasks/untar.yml
    input_mapping:
      input: site-tarball
    output_mapping:
      output: generated-site
  - put: cf-staging
    params:
      manifest: eb-hugo/ci/assets/hugo-manifest-staging.yml

- name: test-staging
  public: false
  serial: true
  plan:
  - get: eb-hugo
  - get: site-tarball
    passed: [deploy-site-staging]
    trigger: true
  - task: smoke-tests
    file: eb-hugo/ci/tasks/smoke-tests.yml
    params:
      HOST: http://eb-hugo-staging.engineerbetter.com

- name: deploy-site-prod
  public: false
  serial: true
  plan:
  - get: eb-hugo
  - get: site-tarball
    passed: [test-staging]
  - task: untar
    file: eb-hugo/ci/tasks/untar.yml
    input_mapping:
      input: site-tarball
    output_mapping:
      output: generated-site
  - put: cf-prod
    params:
      manifest: eb-hugo/ci/assets/hugo-manifest-prod.yml

- name: test-prod
  public: false
  serial: true
  plan:
  - get: eb-hugo
  - get: site-tarball
    passed: [deploy-site-prod]
    trigger: true
  - task: smoke-tests
    file: eb-hugo/ci/tasks/smoke-tests.yml
    params:
      HOST: http://www.engineerbetter.com