---
resources:
- name: eb-hugo
  type: git
  source:
    uri: https://github.com/engineerbetter/engineerbetter-hugo.git

- name: site-tarball
  type: s3
  source:
    bucket: eb-hugo-builds
    region_name: eu-west-2
    versioned_file: eb-hugo-built.tar.gz
    access_key_id: {{concourse_ci_s3_access_key}}
    secret_access_key: {{concourse_ci_s3_secret_key}}

- name: eb-blog
  type: git
  source:
    uri: https://github.com/engineerbetter/engineerbetter.com.git
    branch: blog-only

- name: blog-tarball
  type: s3
  source:
    bucket: engineerbetter-jekyll-builds
    region_name: eu-west-1
    versioned_file: engineerbetter-blog-built.tar.gz
    access_key_id: {{concourse_ci_s3_access_key}}
    secret_access_key: {{concourse_ci_s3_secret_key}}

- name: cf-dev
  type: cf
  source:
    <<: &cf-params
      api: https://api.run.pivotal.io
      username: systems@engineerbetter.com
      password: {{systems_cf_password}}
      organization: engineerbetter
      skip_cert_check: false
    space: development

- name: cf-staging
  type: cf
  source:
    <<: *cf-params
    space: staging

jobs:
- name: build-site
  serial: true
  plan:
  - get: eb-hugo
    trigger: true
  - task: hugo
    file: eb-hugo/ci/tasks/hugo-build.yml
  - aggregate:
    - put: site-tarball
      params:
        file: tarball/eb-hugo-built.tar.gz
    - put: cf-dev
      params:
        manifest: eb-hugo/ci/assets/hugo-manifest-dev.yml

- name: build-blog
  public: false
  serial: true
  plan:
  - get: eb-hugo
    trigger: true
  - get: eb-blog
    trigger: true
  - task: jekyll-build
    file: eb-blog/ci/tasks/jekyll-build.yml
    input_mapping:
      engineerbetter.com: eb-blog
    output_mapping:
      jekyll-built: blog-tarball
  - aggregate:
    - put: blog-tarball
      params:
        file: blog-tarball/engineerbetter-blog-built.tar.gz
    - put: cf-dev
      params:
        manifest: eb-hugo/ci/assets/blog-manifest-dev.yml

- name: test-dev
  public: false
  serial: true
  plan:
  - get: eb-hugo
  - get: site-tarball
    passed: [build-site]
    trigger: true
  - get: blog-tarball
    passed: [build-blog]
    trigger: true
  - task: smoke-tests
    file: eb-hugo/ci/tasks/smoke-tests.yml
    params:
      HOST: eb-hugo-dev.engineerbetter.com

- name: deploy-site-staging
  public: false
  serial: true
  plan:
  - get: eb-hugo
  - get: site-tarball
    passed: [test-dev]
    trigger: true
  - task: untar
    file: eb-hugo/ci/tasks/untar.yml
    input_mapping:
      input: site-tarball
    output_mapping:
      output: generated-site
  - put: cf-staging
    params:
      manifest: eb-hugo/ci/assets/hugo-manifest-staging.yml

- name: deploy-blog-staging
  public: false
  serial: true
  plan:
  - get: eb-hugo
  - get: blog-tarball
    passed: [test-dev]
    trigger: true
  - task: untar
    file: eb-hugo/ci/tasks/untar.yml
    input_mapping:
      input: blog-tarball
    output_mapping:
      output: generated-blog
  - put: cf-staging
    params:
      manifest: eb-hugo/ci/assets/blog-manifest-staging.yml

- name: test-staging
  public: false
  serial: true
  plan:
  - get: eb-hugo
  - get: site-tarball
    passed: [deploy-site-staging]
    trigger: true
  - get: blog-tarball
    passed: [deploy-blog-staging]
    trigger: true
  - task: smoke-tests
    file: eb-hugo/ci/tasks/smoke-tests.yml
    params:
      HOST: eb-hugo-staging.engineerbetter.com