---
resource_types:
- name: cf-cli
  type: registry-image
  source:
    repository: nulldriver/cf-cli-resource
    tag: 2.20.0

resources:
- name: eb-hugo
  type: git
  webhook_token: ((webhook_token))
  source:
    uri: https://github.com/engineerbetter/engineerbetter-hugo.git
- name: drafts-site-tarball
  type: s3
  source:
    bucket: eb-hugo-builds
    region_name: eu-west-2
    versioned_file: eb-hugo-drafts-built.tar.gz
    access_key_id: ((concourse_ci_s3_access_key))
    secret_access_key: ((concourse_ci_s3_secret_key))

- name: site-tarball
  type: s3
  source:
    bucket: eb-hugo-builds
    region_name: eu-west-2
    versioned_file: eb-hugo-built.tar.gz
    access_key_id: ((concourse_ci_s3_access_key))
    secret_access_key: ((concourse_ci_s3_secret_key))

- name: kf-release-deployer-image
  type: registry-image
  source:
    repository: gcr.io/kf-releases/kf-release-deployer
    tag: v2.1.0

- name: kf-pipelines
  type: git
  source:
    uri: git@github.com:EngineerBetter/kf-pipelines.git
    private_key: ((git_private_key))
    branch: prod

jobs:
- name: set-pipeline
  serial: true
  plan:
  - get: eb-hugo
    trigger: true
  - set_pipeline: self
    file: eb-hugo/ci/pipeline.yml

- name: dev
  serial: true
  plan:
  - in_parallel:
    - get: eb-hugo
      passed: [set-pipeline]
      trigger: true
    - get: kf-release-deployer-image
    - get: kf-pipelines
  - task: hugo
    file: eb-hugo/ci/tasks/hugo-build.yml
    params:
      HUGO_BUILDDRAFTS: true
      HUGO_BUILDFUTURE: true
  - &generate-kubeconfig
    task: generate-kubeconfig
    file: kf-pipelines/ci/tasks/generate-kubeconfig/task.yml
    params:
      GOOGLE_CREDENTIALS: ((ebkf-prod-app-developer-creds.gcp_credentials_json))
      REGION: ((ebkf-prod-app-developer-creds.region))
      CLUSTER: ((ebkf-prod-app-developer-creds.cluster_name))
  - task: setup-routes
    file: kf-pipelines/ci/tasks/kubectl/task.yml
    vars:
      kf_version: ((ebkf-prod-version))
    input_mapping:
      input: eb-hugo
    params:
      ARGS: apply -f input/virtual-service-dev.yml
  - task: kf-push
    file: kf-pipelines/ci/tasks/kf-cli/task.yml
    vars:
      kf_version: ((ebkf-prod-version))
    input_mapping:
      manifest: eb-hugo
      input: generated-site
    params:
      ARGS: push --space development --manifest eb-hugo/ci/assets/hugo-manifest-dev.yml --path input
  - task: smoke-tests
    file: eb-hugo/ci/tasks/smoke-tests.yml
    params:
      HOST: https://eb-hugo-dev.engineerbetter.com
  - put: drafts-site-tarball
    params:
      file: tarball/eb-hugo-built.tar.gz

- name: staging
  public: false
  serial: true
  plan:
  - in_parallel:
    - get: eb-hugo
      passed: [dev]
      trigger: true
    - get: kf-release-deployer-image
    - get: kf-pipelines
  - task: hugo
    file: eb-hugo/ci/tasks/hugo-build.yml
  - *generate-kubeconfig
  - task: setup-routes
    file: kf-pipelines/ci/tasks/kubectl/task.yml
    vars:
      kf_version: ((ebkf-prod-version))
    input_mapping:
      input: eb-hugo
    params:
      ARGS: apply -f input/virtual-service-staging.yml
  - task: kf-push
    file: kf-pipelines/ci/tasks/kf-cli/task.yml
    vars:
      kf_version: ((ebkf-prod-version))
    input_mapping:
      manifest: eb-hugo
      input: generated-site
    params:
      ARGS: push --space staging --manifest eb-hugo/ci/assets/hugo-manifest-staging.yml --path input
  - task: smoke-tests
    file: eb-hugo/ci/tasks/smoke-tests.yml
    params:
      HOST: https://eb-hugo-staging.engineerbetter.com
  - put: site-tarball
    params:
      file: tarball/eb-hugo-built.tar.gz

- name: prod
  public: false
  serial: true
  plan:
  - in_parallel:
    - get: generated-site
      resource: site-tarball
      passed: [staging]
      params:
        unpack: true
    - get: eb-hugo
      passed: [staging]
      trigger: true
    - get: kf-release-deployer-image
    - get: kf-pipelines
  - *generate-kubeconfig
  - task: setup-routes
    file: kf-pipelines/ci/tasks/kubectl/task.yml
    vars:
      kf_version: ((ebkf-prod-version))
    input_mapping:
      input: eb-hugo
    params:
      ARGS: apply -f input/virtual-service-prod.yml -f input/virtual-service-redirect-www.yml
  - task: kf-push
    file: kf-pipelines/ci/tasks/kf-cli/task.yml
    vars:
      kf_version: ((ebkf-prod-version))
    input_mapping:
      manifest: eb-hugo
      input: generated-site
    params:
      ARGS: push --space production --manifest eb-hugo/ci/assets/hugo-manifest-prod.yml --path input
  - task: smoke-tests
    file: eb-hugo/ci/tasks/smoke-tests.yml
    params:
      HOST: https://www.engineerbetter.com
