---
resources:
- name: eb-hugo
  type: git
  source:
    uri: https://github.com/engineerbetter/engineerbetter-hugo.git

- name: drafts-site-tarball
  type: s3
  source:
    bucket: eb-hugo-builds
    region_name: eu-west-2
    versioned_file: eb-hugo-drafts-built.tar.gz
    access_key_id: ((concourse_ci_s3_access_key))
    secret_access_key: ((concourse_ci_s3_secret_key))

- name: site-tarball
  type: s3
  source:
    bucket: eb-hugo-builds
    region_name: eu-west-2
    versioned_file: eb-hugo-built.tar.gz
    access_key_id: ((concourse_ci_s3_access_key))
    secret_access_key: ((concourse_ci_s3_secret_key))

- name: cf-dev
  type: cf
  source:
    <<: &cf-params
      api: https://api.run.pivotal.io
      username: systems@engineerbetter.com
      password: ((systems_cf_password))
      organization: engineerbetter
      skip_cert_check: false
    space: development

- name: cf-staging
  type: cf
  source:
    <<: *cf-params
    space: staging

- name: cf-prod
  type: cf
  source:
    <<: *cf-params
    space: production

jobs:
- name: dev
  serial: true
  plan:
  - get: eb-hugo
    trigger: true
  - task: hugo
    file: eb-hugo/ci/tasks/hugo-build.yml
    params:
      HUGO_BUILDDRAFTS: true
      HUGO_BUILDFUTURE: true
  - aggregate:
    - put: drafts-site-tarball
      params:
        file: tarball/eb-hugo-built.tar.gz
    - put: cf-dev
      params:
        manifest: eb-hugo/ci/assets/hugo-manifest-dev.yml
  - task: smoke-tests
    file: eb-hugo/ci/tasks/smoke-tests.yml
    params:
      HOST: http://eb-hugo-dev.engineerbetter.com

- name: staging
  public: false
  serial: true
  plan:
  - get: eb-hugo
    passed: [dev]
    trigger: true
  - task: hugo
    file: eb-hugo/ci/tasks/hugo-build.yml
  - aggregate:
    - put: site-tarball
      params:
        file: tarball/eb-hugo-built.tar.gz
    - put: cf-staging
      params:
        manifest: eb-hugo/ci/assets/hugo-manifest-staging.yml
  - task: smoke-tests
    file: eb-hugo/ci/tasks/smoke-tests.yml
    params:
      HOST: http://eb-hugo-staging.engineerbetter.com

- name: prod
  public: false
  serial: true
  plan:
  - get: eb-hugo
  - get: site-tarball
    passed: [staging]
  - task: untar
    file: eb-hugo/ci/tasks/untar.yml
    input_mapping:
      input: site-tarball
    output_mapping:
      output: generated-site
  - put: cf-prod
    params:
      manifest: eb-hugo/ci/assets/hugo-manifest-prod.yml
  - task: smoke-tests
    file: eb-hugo/ci/tasks/smoke-tests.yml
    params:
      HOST: https://www.engineerbetter.com
