---
resource_types:
- name: cf-cli
  type: registry-image
  source:
    repository: nulldriver/cf-cli-resource
    tag: 2.20.0

resources:
- name: eb-hugo
  type: git
  webhook_token: ((webhook_token))
  source:
    uri: https://github.com/engineerbetter/engineerbetter-hugo.git
- name: drafts-site-tarball
  type: s3
  source:
    bucket: eb-hugo-builds
    region_name: eu-west-2
    versioned_file: eb-hugo-drafts-built.tar.gz
    access_key_id: ((concourse_ci_s3_access_key))
    secret_access_key: ((concourse_ci_s3_secret_key))

- name: site-tarball
  type: s3
  source:
    bucket: eb-hugo-builds
    region_name: eu-west-2
    versioned_file: eb-hugo-built.tar.gz
    access_key_id: ((concourse_ci_s3_access_key))
    secret_access_key: ((concourse_ci_s3_secret_key))

- name: kf-release-deployer-image
  type: registry-image
  source:
    repository: gcr.io/kf-releases/kf-release-deployer
    tag: v2.1.0

- name: concourse-tasks
  type: git
  icon: github
  source:
    uri: git@github.com:EngineerBetter/concourse-tasks.git
    private_key: ((git_private_key))

jobs:
- name: set-pipeline
  serial: true
  plan:
  - get: eb-hugo
    trigger: true
  - set_pipeline: self
    file: eb-hugo/ci/pipeline.yml

- name: dev
  serial: true
  plan:
  - in_parallel:
    - get: eb-hugo
      passed: [set-pipeline]
      trigger: true
    - get: concourse-tasks
    - get: kf-release-deployer-image
  - in_parallel:
    - task: hugo
      file: eb-hugo/ci/tasks/hugo-build.yml
      params:
        HUGO_BUILDDRAFTS: true
        HUGO_BUILDFUTURE: true
  - in_parallel:
    - put: drafts-site-tarball
      params:
        file: tarball/eb-hugo-built.tar.gz
    - task: kf-push
      file: eb-hugo/ci/tasks/kf-push.yml
      image: kf-release-deployer-image
      params:
        SPACE: development
        MANIFEST: ci/assets/hugo-manifest-dev.yml
        GOOGLE_CREDENTIALS: ((ebkf-prod-app-developer-creds.gcp_credentials_json))
  - task: smoke-tests
    file: eb-hugo/ci/tasks/smoke-tests.yml
    params:
      HOST: https://eb-hugo-dev.engineerbetter.com

- name: staging
  public: false
  serial: true
  plan:
  - in_parallel:
    - get: eb-hugo
      passed: [dev]
      trigger: true
    - get: concourse-tasks
    - get: kf-release-deployer-image
  - in_parallel:
    - task: hugo
      file: eb-hugo/ci/tasks/hugo-build.yml
  - in_parallel:
    - put: site-tarball
      params:
        file: tarball/eb-hugo-built.tar.gz
    - task: kf-push
      file: eb-hugo/ci/tasks/kf-push.yml
      image: kf-release-deployer-image
      params:
        SPACE: staging
        MANIFEST: ci/assets/hugo-manifest-staging.yml
        GOOGLE_CREDENTIALS: ((ebkf-prod-app-developer-creds.gcp_credentials_json))
  - task: smoke-tests
    file: eb-hugo/ci/tasks/smoke-tests.yml
    params:
      HOST: https://eb-hugo-staging.engineerbetter.com

- name: prod
  public: false
  serial: true
  plan:
  - in_parallel:
    - get: generated-site
      resource: site-tarball
      passed: [staging]
      params:
        unpack: true
    - get: eb-hugo
      passed: [staging]
      trigger: true
    - get: concourse-tasks
    - get: kf-release-deployer-image
  - task: kf-push
    file: eb-hugo/ci/tasks/kf-push.yml
    image: kf-release-deployer-image
    params:
      SPACE: production
      MANIFEST: ci/assets/hugo-manifest-prod.yml
      GOOGLE_CREDENTIALS: ((ebkf-prod-app-developer-creds.gcp_credentials_json))
  - task: smoke-tests
    file: eb-hugo/ci/tasks/smoke-tests.yml
    params:
      HOST: https://www.engineerbetter.com
