---
resource_types:
- name: cf-cli
  type: registry-image
  source:
    repository: nulldriver/cf-cli-resource
    tag: 2.20.0

resources:
- name: eb-hugo
  type: git
  webhook_token: ((webhook_token))
  source:
    uri: https://github.com/engineerbetter/engineerbetter-hugo.git

- name: drafts-site-tarball
  type: s3
  source:
    bucket: eb-hugo-builds
    region_name: eu-west-2
    versioned_file: eb-hugo-drafts-built.tar.gz
    access_key_id: ((concourse_ci_s3_access_key))
    secret_access_key: ((concourse_ci_s3_secret_key))

- name: site-tarball
  type: s3
  source:
    bucket: eb-hugo-builds
    region_name: eu-west-2
    versioned_file: eb-hugo-built.tar.gz
    access_key_id: ((concourse_ci_s3_access_key))
    secret_access_key: ((concourse_ci_s3_secret_key))

- name: cf
  type: cf-cli
  source:
    cf_cli_version: 7
    api: https://api.system.ebcf.engineerbetter.com
    username: systems@engineerbetter.com
    password: ((systems_cf_password))
    org: engineerbetter
    skip_cert_check: false
    space: development

jobs:
- name: dev
  serial: true
  plan:
  - get: eb-hugo
    trigger: true
  - task: hugo
    file: eb-hugo/ci/tasks/hugo-build.yml
    params:
      HUGO_BUILDDRAFTS: true
      HUGO_BUILDFUTURE: true
  - in_parallel:
    - put: drafts-site-tarball
      params:
        file: tarball/eb-hugo-built.tar.gz
    - put: cf
      params:
        command: push
        strategy: rolling
        manifest: eb-hugo/ci/assets/hugo-manifest-dev.yml
  - task: smoke-tests
    file: eb-hugo/ci/tasks/smoke-tests.yml
    params:
      HOST: http://eb-hugo-dev.engineerbetter.com

- name: staging
  public: false
  serial: true
  plan:
  - get: eb-hugo
    passed: [dev]
    trigger: true
  - task: hugo
    file: eb-hugo/ci/tasks/hugo-build.yml
  - in_parallel:
    - put: site-tarball
      params:
        file: tarball/eb-hugo-built.tar.gz
    - put: cf
      params:
        command: push
        strategy: rolling
        space: staging
        manifest: eb-hugo/ci/assets/hugo-manifest-staging.yml
  - task: smoke-tests
    file: eb-hugo/ci/tasks/smoke-tests.yml
    params:
      HOST: http://eb-hugo-staging.engineerbetter.com

- name: prod
  public: false
  serial: true
  plan:
  - get: eb-hugo
  - get: generated-site
    resource: site-tarball
    passed: [staging]
    params:
      unpack: true
  - put: cf
    params:
      command: push
      strategy: rolling
      space: production
      manifest: eb-hugo/ci/assets/hugo-manifest-prod.yml
  - task: smoke-tests
    file: eb-hugo/ci/tasks/smoke-tests.yml
    params:
      HOST: https://www.engineerbetter.com
