---
resources:
- name: eb-hugo
  type: git
  source:
    uri: https://github.com/engineerbetter/engineerbetter-hugo.git

- name: site-tarball
  type: s3
  source:
    bucket: eb-hugo-builds
    region_name: eu-west-2
    versioned_file: eb-hugo-built.tar.gz
    access_key_id: {{concourse_ci_s3_access_key}}
    secret_access_key: {{concourse_ci_s3_secret_key}}

- name: eb-blog
  type: git
  source:
    uri: https://github.com/engineerbetter/engineerbetter.com.git
    branch: blog-only

- name: blog-tarball
  type: s3
  source:
    bucket: engineerbetter-jekyll-builds
    region_name: eu-west-1
    versioned_file: engineerbetter-blog-built.tar.gz
    access_key_id: {{concourse_ci_s3_access_key}}
    secret_access_key: {{concourse_ci_s3_secret_key}}

- name: cf-dev
  type: cf
  source:
    api: https://api.run.pivotal.io
    username: systems@engineerbetter.com
    password: {{systems_cf_password}}
    organization: engineerbetter
    space: development
    skip_cert_check: false

jobs:
- name: build-site
  serial: true
  plan:
  - get: eb-hugo
    trigger: true
  - task: hugo
    file: eb-hugo/ci/tasks/hugo-build.yml
  - aggregate:
    - put: site-tarball
      params:
        file: tarball/eb-hugo-built.tar.gz
    - put: cf-dev
      params:
        manifest: eb-hugo/ci/assets/hugo-manifest-dev.yml

- name: build-blog
  public: false
  serial: true
  plan:
  - get: eb-hugo
  - get: eb-blog
    trigger: true
  - task: jekyll-build
    file: eb-blog/ci/tasks/jekyll-build.yml
    input_mapping:
      engineerbetter.com: eb-blog
    output_mapping:
      jekyll-built: blog-tarball
  - aggregate:
    - put: blog-tarball
      params:
        file: blog-tarball/engineerbetter-blog-built.tar.gz
    - put: cf-dev
      params:
        manifest: eb-hugo/ci/assets/blog-manifest-dev.yml